### ISSUE TITLE
easyloop does not work

### ISSUE THREAD

**Issue by uppercaseVar** [sguduguntla/Easy-Loop-Extension#2]

**Comment by uppercaseVar** [comment]
I wanted to see what my grade would be if I turned in an assignment and easyloop was gone. When I pull up the easyloop site on the chrome webstore I got a 404 error and if I try to search for it on the website it doesn't show up. Please fix this I loved easyloop.

**Comment by sguduguntla** [comment]
Hi Bob,

Thanks for opening an issue. Unfortunately, Easy Loop is currently under maintenance and will be down for installation (for new users). It will be back up within the next two weeks. Follow the Facebook page at @schoolloopeasyloop for more updates.

**Comment by sguduguntla** [comment]
Hi Bob,

Easy Loop has been published again. You should be able to install it without any problems now. Thank you for your patience.
